artstore/urls.py
from django.urls import path
# dot is relative import of the same folder we are import views
from . import views
# this app_name is useful for addressing the urls in templates
# this is used to make dynamic urls in html template files
app_name = "artstore"

# as we are directed by ecommarts urls.py file to this file
# now the server look into the urls of the current app
# to display a view which is imported above
# empty quotes represent index or homepage.
urlpatterns = [
    path('', views.home_page, name='homepage'),
    path('store/', views.store, name='store'),
    path('search/', views.search_product, name='search'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('processCheckout', views.process_checkout, name='processCheckout'),
    path('register/', views.user_registration, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('orders/', views.orders, name='orders')
]

ecommarts/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# this is the first route(path) django server will be directed to
# from here we include the artstore.urls
# so it will look for an 'app' named artstore
# and the server is then directed to urls file of artstore
urlpatterns = [
    path('', include('artstore.urls')),
    path('admin/', admin.site.urls),
]

# adding images url to the list of routes for dynamic images
# MEDIA_URL and MEDIA_ROOT are defined in settings.py
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artstore/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


# each model corresponds to a table in database
# for banner area only 3 images are supported as can be seen in home_page in views.py
class BannerImage(models.Model):
    image = models.ImageField()
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.image}"


# customer registration model
class Customer(models.Model):
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.email}"


# product category model
class Category(models.Model):
    # we don't need id field as django gives us that by default
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    # just so the plural name of category model is appropriately in admin area
    # without this django will add just an 's' ie categorys which is stupid
    class Meta:
        verbose_name_plural = 'Categories'


# product model
# each product belong to a category
# as in category field the type is Foreignkey which means product is related to category
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    image = models.ImageField()
    # if you delete the category all products related to that will be deleted
    # here model.CASCADE just do that
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    # this is used to print string representation of an model object
    # whenever we print product its name will be printed instead of some object
    def __str__(self):
        return self.name


# order model
# contain the action order
# this order can have many items just like a category can have many products
# it have also relation to customer as customer can place order only
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order_date = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)


# Order Item model
# represent a single item and its quantity
# related to product and order with foreignkey
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now=True)


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zipcode = models.CharField(max_length=200)
    country = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)


# these are called signals in django
# can think of as javascript events
# here whenever an object is deleted from database post_delete signal is fired
# then we make sure to delete the image when image field is deleted
# as django will not delete the image but only the imagepath
# so this is to make sure the image is also deleted after its field is deleted

# https://stackoverflow.com/questions/16041232/django-delete-filefield
# Whenever ANY model is deleted, if it has a file field on it, delete the associated file too
@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    print(sender, instance)
    for field in sender._meta.concrete_fields:
        if isinstance(field, models.FileField):
            instance_file_field = getattr(instance, field.name)
            delete_file_if_unused(sender, instance, field, instance_file_field)


# Delete the file if something else get uploaded in its place
@receiver(pre_save)
def delete_files_when_file_changed(sender, instance, **kwargs):
    # Don't run on initial save
    if not instance.pk:
        return
    for field in sender._meta.concrete_fields:
        if isinstance(field, models.FileField):
            # its got a file field. Let's see if it changed
            try:
                instance_in_db = sender.objects.get(pk=instance.pk)
            except sender.DoesNotExist:
                # We are probably in a transaction and the PK is just temporary
                # Don't worry about deleting attachments if they aren't actually saved yet.
                return
            instance_in_db_file_field = getattr(instance_in_db, field.name)
            instance_file_field = getattr(instance, field.name)
            if instance_in_db_file_field.name != instance_file_field.name:
                delete_file_if_unused(sender, instance, field, instance_in_db_file_field)


# Only delete the file if no other instances of that model are using it
def delete_file_if_unused(model, instance, field, instance_file_field):
    dynamic_field = {field.name: instance_file_field.name}
    print(dynamic_field)
    # https://stackoverflow.com/questions/310732/in-django-how-does-one-filter-a-queryset-with-dynamic-field-lookups
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)

artstore/views.py
from django.shortcuts import render, redirect, reverse
from django.utils.html import escape, strip_tags
from django.http import HttpResponse
import json
from .helper import str_convert_single_quotes
from .models import Product, Customer, Order, OrderItem, ShippingAddress, Category, BannerImage
from .forms import CustomerRegistrationForm, CustomerLoginForm


# start page
def home_page(request):
    # get the latest 3 images as limit is [:3]
    bannerImages = BannerImage.objects.all().order_by('-date_added')[:3]
    categories = Category.objects.all()
    category_list_with_product_set = []
    for category in categories:
        category_product_set = category.product_set.get_queryset()
        category_list_with_product_set.append(category_product_set)
    # context variable is used throughout views.py to pass dynamic data to html templates
    context = {
        'categories': categories,
        'images': bannerImages
    }
    return render(request, 'artstore/homepage.html', context)


# store page
def store(request):
    # limit to 100 products
    products = Product.objects.all()[0:100]
    context = {'products': products}
    return render(request, 'artstore/store.html', context)


# product search page
def search_product(request):
    query = request.GET.get('q')
    if query:
        query = escape(strip_tags(query))
        result = Product.objects.filter(name__contains=query)
        if result:
            context = {'products': result, 'query': query}
            return render(request, 'artstore/search.html', context)
        else:
            context = {'producsts': result, 'query': query}
            return render(request, 'artstore/search.html', context)


# cart page
def cart(request):
    context = {}
    return render(request, 'artstore/cart.html', context)


# orders page
def orders(request):
    # get the logged in user from session
    session_customer = request.session.get('customer')
    if session_customer:
        orders_q = Order.objects.filter(customer__pk=session_customer[0])
        if orders_q:
            order_item_list = []
            for order in orders_q:
                # order item
                # get all the items contain in this this order ie. orders_q
                # form order model we can get all the items in orderitem table thanks for foreignkey relationships
                oi = order.orderitem_set.get_queryset()
                # as the name imply order_item_list contains all orderItems of all order
                # for this logged in user
                order_item_list.append(oi)
            context = {'orders': order_item_list}
            return render(request, 'artstore/orders.html', context)
        else:
            context = {}
            return render(request, 'artstore/orders.html', context)
    else:
        return redirect(reverse('artstore:login'))


# checkout page
def checkout(request):
    context = {}
    return render(request, 'artstore/checkout.html', context)


# process checkout page
def process_checkout(request):
    # get request is not allowed
    if request.method == "GET":
        return redirect(reverse('artstore:homepage'))
    if request.method == 'POST':
        # if user is not logged in
        if not request.session.get('customer'):
            context = {
                'msg': 'please login to complete checkout',
                'redirect': request.build_absolute_uri(reverse('artstore:login'))
            }
            return render(request, 'artstore/message.html', context)
        # get cart as string form checkout page
        cartString = request.POST.get('cart')
        # convert the cart string to actual python list
        cart = json.loads(str_convert_single_quotes(cartString))

        # if cart is empty
        if len(cart) < 1:
            context = {
                'msg': 'your cart can not be empty..!',
                'redirect': request.build_absolute_uri(reverse('artstore:store'))
            }
            return render(request, 'artstore/message.html', context)

        # get shipping info form field
        address = request.POST.get('address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        zipcode = request.POST.get('zipcode')
        country = request.POST.get('country')

        # add order to order table
        # get customer who is making the order
        # this is customer list with customerID and email we need id here
        session_customer = request.session.get('customer')
        customer = Customer.objects.get(pk=session_customer[0])
        # if we get a customer from db for session customer
        if customer:
            # create order here
            order = Order(customer=customer)
            order.save()
            # get the order just created above
            latest_order = Order.objects.latest('id')
            # loop through the whole cart
            for item in cart:
                # get product to put in order item table/model
                product = Product.objects.get(pk=item.get('id'))
                if product:
                    # insert each item/product with quantity to order item table/model
                    orderItem = OrderItem(product=product, order=latest_order, quantity=item.get('quantity'))
                    orderItem.save()
                    # pass
            # insert shipping detail
            shipping = ShippingAddress(customer=customer, order=latest_order, address=address, city=city, state=state, zipcode=zipcode, country=country)
            shipping.save()
            context = {
                'msg': 'your order is successfully processed..!',
                'redirect': request.build_absolute_uri(reverse('artstore:store')),
                'action': 'clearCart'
            }
            return render(request, 'artstore/message.html', context)
    else:
        return HttpResponse('404 Not Found..')


def user_registration(request):
    # go to store if user is logged in
    if request.session.get('customer'):
        # reverse is used to get the actual url for the view "store"
        # we can do so because we have app_name variable in urls.py
        return redirect(reverse('artstore:store'))
    if request.method == 'GET':
        form = CustomerRegistrationForm()
        context = {'form': form}
        return render(request, 'artstore/register.html', context)
    if request.method == 'POST':
        form = CustomerRegistrationForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            # check if this email already exist
            q = Customer.objects.filter(email=clean_data['email_field'])
            if q:
                form.add_error('email_field', 'Email already exists')
            else:
                customer = Customer(email=clean_data['email_field'],
                                    password=clean_data['password_field'])
                customer.save()
                context = {
                    'msg': 'you are now registered',
                    'redirect': request.build_absolute_uri(reverse('artstore:login'))
                }
                return render(request, 'artstore/message.html', context)
        context = {'form': form}
        return render(request, 'artstore/register.html', context)


def user_login(request):
    # go to store if user is logged in
    if request.session.get('customer'):
        return redirect(reverse('artstore:store'))
    if request.method == 'GET':
        form = CustomerLoginForm()
        context = {'form': form}
        return render(request, 'artstore/login.html', context)
    if request.method == 'POST':
        form = CustomerLoginForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            # check for user in database
            customer = Customer.objects.filter(email=clean_data['email_field']).first()
            if customer is not None:
                if customer.email == clean_data['email_field'] and \
                        customer.password == clean_data['password_field']:
                    # customer credentials is ok
                    # add customer to session
                    request.session['customer'] = [customer.id, customer.email]
                    request.session.set_expiry(0)
                    return redirect(reverse('artstore:store'))
                else:
                    form.add_error('email_field', 'invalid user name or password')
            else:
                form.add_error('email_field', 'invalid user name or password')
        context = {'form': form}
        return render(request, 'artstore/login.html', context)


def user_logout(request):
    if request.method == "POST":
        try:
            del request.session['customer']
            request.session.flush()
            return redirect(reverse('artstore:login'))
        except KeyError:
            return redirect(reverse('artstore:store'))
    if request.method == "GET":
        return HttpResponse('404 not found..')

artstore/templates/artstore/cart.html
{% extends 'artstore/layout.html' %}
{% load static %}
{% block content %}
	<div class="cart-container mt-5">
		<div class="row">
			<div class="col-lg-12">
				<div class="box-element">

					<a  class="btn btn-outline-dark" href="{% url 'artstore:store' %}">&#x2190; Back to Store</a>

					<br>
					<br>
					<table class="table">
						<tr>
							<th><h5>Items: <strong id="item-quantity">{{order.get_cart_items}}</strong></h5></th>
							<th><h5>Total:<strong id="item-total"> ${{order.get_cart_total|floatformat:2}}</strong></h5></th>
							<th>
								<a  style="float:right; margin:5px;" class="btn btn-dark" href="{% url 'artstore:checkout' %}">Checkout</a>
							</th>
						</tr>
					</table>

				</div>

				<br>
				<div class="table-container">
					<!--place table here-->
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col"></th>
                          <th scope="col">Item</th>
                          <th scope="col">Price</th>
                          <th scope="col">Quantity</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody id="dynamic-cart-items">
                        <!--dynamic cart items rows-->
                      </tbody>
                    </table>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

artstore/templates/artstore/checkout.html
{% extends 'artstore/layout.html' %}

{% block content %}
    <div class="checkout-container mt-5">
        <div class="row">
            <div class="col-lg-6">
                <div class="box-element" id="form-wrapper">
                    <form id="checkout-form" action="{% url 'artstore:processCheckout' %}" method="POST">
                        {% csrf_token %}
                        <div id="shipping-info">
                            <p>Shipping Information:</p>
                            <div class="form-field pad-bottom">
                                <input class="form-control" type="text" name="address" placeholder="Address.." required>
                            </div>
                            <div class="form-field pad-bottom">
                                <input class="form-control" type="text" name="city" placeholder="City.." required>
                            </div>
                            <div class="form-field pad-bottom">
                                <input class="form-control" type="text" name="state" placeholder="State.." required>
                            </div>
                            <div class="form-field pad-bottom">
                                <input class="form-control" type="text" name="zipcode" placeholder="Zip code.." required>
                            </div>
                            <div class="form-field pad-bottom">
                                <input class="form-control" type="text" name="country" placeholder="country.." required>
                            </div>
                        </div>
                        <div id="cart-field">

                        </div>
                        <input id="form-button" class="btn btn-warning btn-block" type="submit" value="Continue">
                    </form>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="box-element">
                    <a  class="btn btn-outline-dark" href="{% url 'artstore:cart' %}">&#x2190; Back to Cart</a>
                    <hr>
                    <h3>Order Summary</h3>
                    <hr>
                    <div id="cart-row-container">
                    <!--dynamic rows-->
                    </div>
                    <div id="summary-container">
                    <!--  dynamic summary  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}>

artstore/templates/artstore/homepage.html
{% extends 'artstore/layout.html' %}
{% load static %}

{% block content %}
<!-- hero section -->
    <div class="hero-section">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
              {% for image in images %}
                  <!--if this is first iteration add active class-->
                  {% if forloop.first %}
                      <div class="carousel-item active">
                          <img class="d-block w-100" src="{{image.image.url}}" alt="First slide">
                      </div>
                  {% endif %}
                <div class="carousel-item">
                  <img class="d-block w-100" src="{{image.image.url}}" alt="Second slide">
                </div>
              {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div> <!-- hero section -->


<!--category loop-->
{% for category in categories %}
    <div class="row">
      <div class="col-12 mb-3 mt-3">
        <h1 class="h5">Category: <span class="font-weight-bold">{{ category.name|title }}</span></h1>
      </div>
        {% if category.product_set.get_queryset %}
        <!--product loop-->
        {% for product in category.product_set.get_queryset|slice:":3" %}
          <!--product card-->
          <div class="col-4 mb-4">
            <img class="thumbnail" src="{{ product.image.url }}">
            <div class="box-element product">
                <h6><strong>{{product.name | capfirst }}</strong></h6>
                <hr>

                <button data-name="{{product.name}}" data-image="{{product.image.url}}" data-product="{{product.id}}" data-price="{{ product.price }}" data-action="add-once" class="btn btn-warning add-btn update-cart">Add to Cart</button>

                <!--<a class="btn btn-outline-secondary" href="#">View</a>-->
                <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>
            </div>
          </div><!--product card-->
        {% endfor %}<!--product loop-->
        {% else %}
            <!--product card-->
          <div class="col-4 mb-4">
            <img class="thumbnail" src="">
            <div class="box-element product">
                <h6><strong>No product in this Category</strong></h6>
                <hr>
                <button class=" disabled  btn btn-warning add-btn update-cart" disabled>Add to Cart</button>
            </div>
          </div><!--product card-->
        {% endif %}

    </div>
  {% endfor %}<!--category loop-->

{% endblock content %}

artstore/templates/artstore/layout.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Art Store</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="icon" type="image/png" href="{% static 'images/cart.png' %}"/>

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" >
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #27384c !important;">
	  <a class="navbar-brand text-light" href="{% url 'artstore:homepage' %}">ArtStore</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
              <a class="nav-link text-light" href="{% url 'artstore:store' %}">Store </a>
            </li>
            {% if request.session.customer %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'artstore:orders' %}">Orders </a>
            </li>
            {% endif %}

        </ul>
	    <div class="form-inline my-2 my-lg-0">

            <a href="{% url 'artstore:cart' %}">
                <img  id="cart-icon" src="{% static 'images/cart.png' %}" alt="cart icon" width="35px">
            </a>
            <p ><span class="rounded bg-info p-1" id="cart-total">0</span></p>
            {% if request.session.customer %}
                <form action="{% url 'artstore:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-warning ml-2">Logout</button>
                </form>
            {% else %}
                <a href="{% url 'artstore:register' %}" class="btn btn-sm btn-warning ml-2">Sign Up</a>
    	     	<a href="{% url 'artstore:login' %}" class="btn btn-sm btn-warning ml-2">Login</a>
            {% endif %}

            {% if request.resolver_match.url_name == 'homepage' or request.resolver_match.url_name == 'store' or request.resolver_match.url_name == 'search' %}
                <form action="{% url 'artstore:search' %}" class="form-inline my-2 my-lg-0 ml-2" method="GET">
                    <input class="form-control mr-sm-2 " type="search" name="q" placeholder="Search Products" aria-label="Search">
                    <button class="btn btn-sm btn-secondary text-white my-2 my-sm-0" type="submit">Search</button>
                </form>
            {% endif %}

	    </div>
	  </div>
	</nav>


    <main>
        <div class="container">
            {% block content %}


            {% endblock content %}
        </div>
    </main>

    <footer class="footer mt-5">
      <div class="container">
        <div class="footer">
            <span class="text-muted">copyright 2021</span>
        </div>
      </div>
    </footer>

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

artstore/templates/artstore/login.html
{% extends 'artstore/layout.html' %}
{% load static %}

{% block content %}
    <div class="w-100 d-flex justify-content-center align-content-center mt-5">
        <div class="sign-in-box">
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <button class="btn btn-lg btn-dark btn-block" type="submit">Login</button>
            </form>
            <div class="m-2"></div>
            <p class="p text-center">don't have an account <a href="{% url 'artstore:register' %}"><strong>Register</strong></a> instead</p>
        </div>
    </div>
{% endblock %}

artstore/templates/artstore/message.html
{% if action == "clearCart" %}
    <script>
        alert("{{ msg }}");
        localStorage.removeItem('cart');
        window.location.replace("{{redirect}}");
    </script>
{% else %}
    <script>
        alert("{{ msg }}");
        window.location.replace("{{redirect}}");
    </script>
{% endif %}

artstore/templates/artstore/orders.html
{% extends 'artstore/layout.html' %}
{% load static %}

{% block content %}
    <div class="row mt-5">
        <div class="col-12">
            <h4 class="h4">Orders Items</h4>
        </div>
        <div class="col-12">
            <div class="table-container">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">Order Id</th>
                      <th scope="col">Product</th>
                      <th scope="col">Price</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Order Date</th>
                      <th scope="col">Complete Status</th>
                    </tr>
                  </thead>
                  <tbody >
                    {% for orderitem_set in orders %}
                        {% for orderItem in orderitem_set %}
                            <tr>
                              <th scope="row">{{orderItem.order.id}}</th>
                              <td>{{orderItem.product.name}}</td>
                              <td>$ {{orderItem.product.price}}</td>
                              <td>{{orderItem.quantity}}</td>
                              <td>{{orderItem.date_added}}</td>
                              <td>{{orderItem.order.is_completed}}</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

artstore/templates/artstore/processCheckout.html
{% extends 'artstore/layout.html' %}

{% block content %}
    <h5>process checkout {{ method }}</h5>
{% endblock content %}>

artstore/templates/artstore/register.html
{% extends 'artstore/layout.html' %}
{% load static %}

{% block content %}
    <div class="w-100 d-flex justify-content-center align-content-center mt-5">
        <div class="sign-in-box">
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <button class="btn btn-lg btn-dark btn-block" type="submit">Register</button>
            </form>
            <div class="m-2"></div>
            <p class="p text-center">already have an account <a href="{% url 'artstore:login' %}"><strong>login</strong></a> instead</p>
        </div>
    </div>
{% endblock %}

artstore/templates/artstore/search.html
{% extends 'artstore/layout.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-2">
            {% if products %}
                <h1 class="h5 font-weight-bold">you search for.. "{{ query }}"</h1>
            {% endif %}
        </div>
        <!-- product loop -->
        {% if products %}
            {% for product in products %}
              <!--product card-->
              <div class="col-4 mb-4">
                <img class="thumbnail" src="{{ product.image.url }}">
                <div class="box-element product">
                    <h6><strong>{{product.name | capfirst }}</strong></h6>
                    <hr>

                    <button data-name="{{product.name}}" data-image="{{product.image.url}}" data-product="{{product.id}}" data-price="{{ product.price }}" data-action="add-once" class="btn btn-warning add-btn update-cart">Add to Cart</button>

                    <!--<a class="btn btn-outline-secondary" href="#">View</a>-->
                    <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>
                </div>
              </div><!--product card-->
            {% endfor %}<!--product loop-->
        {% else %}
            <h1 class="h5">can not find any products for  "{{ query }}" try <a href="{% url 'artstore:store' %}"><stron>Store</stron></a> instead</h1>
        {% endif %}
    </div>
{% endblock content %}